import { ArrowRight, Building2, BriefcaseBusiness, CircleDot, Compass, Layers3, Rocket, ShoppingBag, Store, UsersRound } from "lucide-react";
import { Link, useRoute } from "wouter";
import { footerPages, getUseCase, type FooterPageKey, useCases } from "@/content/useCases";
import { ButtonLink, FinalCta, MarketingLayout, PageHero, SectionHeading } from "@/components/marketing/SiteShell";

const useCaseIcons = { "small-business": Store, ecommerce: ShoppingBag, agencies: BriefcaseBusiness, enterprise: Building2, startups: Rocket };

export function UseCasesPage() {
  return (
    <MarketingLayout>
      <section className="use-cases-hero"><div className="shell use-cases-hero__grid"><div><p className="eyebrow eyebrow--light"><span /> Use Cases</p><h1>One AI workforce.<br /><em>Different operating realities.</em></h1><p>Choose the context closest to your team. Each use case shows how agents DX can create a more useful rhythm between incoming signals, practical action, and human judgement.</p><div className="button-row button-row--start"><ButtonLink href="/contact" variant="primary">Get Started</ButtonLink><ButtonLink href="/contact" variant="outline">Book a Demo</ButtonLink></div></div><aside className="use-cases-hero__matrix"><p>DEPLOYMENT SELECTOR</p><div><span>01</span><strong>Context</strong><small>Where work starts</small></div><div><span>02</span><strong>Workforce role</strong><small>What the agent owns</small></div><div><span>03</span><strong>Human moment</strong><small>Where judgement enters</small></div></aside></div></section>
      <section className="use-case-select-section"><div className="shell"><SectionHeading eyebrow="Choose your context" title={<>Design the workforce around the <em>work in front of you.</em></>} intro="These are deployment perspectives—not one-size-fits-all templates. Start with the operating reality, then decide what better momentum should look like." /><div className="use-case-grid">{useCases.map((useCase, index) => { const Icon = useCaseIcons[useCase.slug]; return <Link key={useCase.slug} href={`/use-cases/${useCase.slug}`} className={`use-case-card use-case-card--${index + 1}`}><div className="use-case-card__top"><span>0{index + 1}</span><Icon size={25} strokeWidth={1.7} /></div><h2>{useCase.label}</h2><p>{useCase.mission}</p><div className="use-case-card__footer"><span>Explore use case</span><ArrowRight size={17} /></div></Link>; })}</div></div></section>
      <section className="use-case-principles"><div className="shell"><p className="eyebrow eyebrow--light"><span /> The shared system</p><h2>Every context needs the same <em>clarity of responsibility.</em></h2><div>{[["Context", "Preserve the details that make the next action useful."], ["Role", "Give the workforce a real job—not an undefined layer of activity."], ["Human moment", "Make expert attention visible at the moments that change the outcome."]].map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
      <FinalCta title={<>Not sure which operating context fits? <em>Start with the work.</em></>} />
    </MarketingLayout>
  );
}

export function UseCaseDetailPage() {
  const [, params] = useRoute("/use-cases/:slug");
  const useCase = getUseCase(params?.slug ?? "");
  if (!useCase) return <MarketingLayout><section className="route-not-found"><div className="shell"><p className="eyebrow"><span /> Use case not found</p><h1>This workforce context is not in the system.</h1><ButtonLink href="/use-cases" variant="primary">Explore Use Cases</ButtonLink></div></section></MarketingLayout>;
  const Icon = useCaseIcons[useCase.slug];
  return <MarketingLayout><PageHero eyebrow={useCase.eyebrow} title={<>{useCase.title.split("<em>")[0]}<em>{useCase.title.match(/<em>(.*?)<\/em>/)?.[1]}</em></>} intro={useCase.intro} aside={<><p className="aside-label">Workforce mission</p><h3>{useCase.mission}</h3><p>Use context to shape the role before you automate the action.</p></>} /><section className="use-case-brief"><div className="shell"><div className="use-case-brief__icon"><Icon size={30} strokeWidth={1.6} /></div><div><p>OPERATING RHYTHM</p><strong>{useCase.rhythm}</strong></div><div><p>HUMAN MOMENT</p><strong>{useCase.humanMoment}</strong></div></div></section><section className="use-case-detail-section"><div className="shell"><SectionHeading eyebrow="The operating sequence" title={<>A practical rhythm for <em>{useCase.label.toLowerCase()}</em> teams.</>} /><div className="use-case-step-grid">{useCase.steps.map((step, index) => <article key={step.title}><span>0{index + 1}</span><CircleDot size={20} strokeWidth={1.7} /><h3>{step.title}</h3><p>{step.text}</p></article>)}</div></div></section><section className="use-case-capabilities"><div className="shell"><div><p className="eyebrow eyebrow--light"><span /> Workforce design</p><h2>Give the system a role your team can <em>recognise.</em></h2></div><ul>{useCase.capabilities.map((capability, index) => <li key={capability}><span>0{index + 1}</span>{capability}<ArrowRight size={17} /></li>)}</ul></div></section><FinalCta title={<>Ready to shape this workforce around your <em>actual operating context?</em></>} /></MarketingLayout>;
}

export function FooterLandingPage({ page }: { page: FooterPageKey }) {
  const content = footerPages[page];
  const icons = [Layers3, Compass, UsersRound, Building2];
  return <MarketingLayout><PageHero eyebrow={content.eyebrow} title={<>{content.title.split("<em>")[0]}<em>{content.title.match(/<em>(.*?)<\/em>/)?.[1]}</em></>} intro={content.intro} aside={<><p className="aside-label">agents DX signal</p><h3>{content.prompt}</h3><p>Build the next step around practical clarity.</p></>} /><section className="footer-page-section"><div className="shell"><p className="eyebrow"><span /> The building blocks</p><div className="footer-page-section__grid">{content.areas.map((area, index) => { const Icon = icons[index]; return <article key={area}><span>0{index + 1}</span><Icon size={25} strokeWidth={1.6} /><h2>{area}</h2><p>{page === "brand-guidelines" ? "A core element of the agents DX expression, designed to keep the signal consistent across every surface." : "A practical design area for creating a workforce that makes the next action more visible and more useful."}</p></article>; })}</div></div></section><section className="footer-page-prompt"><div className="shell"><p className="eyebrow eyebrow--light"><span /> Next move</p><h2>{content.prompt}</h2><p>Bring the operating context. We will help you create a more deliberate path from signal to action.</p><ButtonLink href="/contact" variant="primary">{content.cta}</ButtonLink></div></section></MarketingLayout>;
}
